---
- hosts: all
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install security updates for Tomcat
      apt:
        name: "tomcat*"
        state: latest
        update_cache: yes
        # security: yes
        security: yes

    - name: Restart Tomcat service
      service:
        name: tomcat
        state: restarted
